### ISSUE TITLE
Provide Precomputed Results in Readme

### ISSUE THREAD

**Issue by hashcashier** [nirenzang/PoWSecurity#1]
Hi Ren,

Let me preface this by saying that I'm a fan of the amazing work you've done here.

I believe it would be helpful if you would include in the readme the numerical values of the results you computed and used to make your plots in your published work. That way, newcomers to your repo interested in the results numerically rather than graphically don't have to install matlab and recompute everything unless they really want to double-check your work. This would also spare other researchers who want to use your results as a comparison points some pain.

All the best!

**Comment by nirenzang** [comment]
Thank you so much for the suggestion! I appreciate it. Will do it in the next few days!

**Comment by hashcashier** [comment]
Thanks!
